name: Prepare Workspace
description: Install python, poetry, deps

inputs:
  python-version:
    description: "Python Version"
    required: true
    default: "3.10.0"
  poetry-version:
    description: "Poetry Version"
    required: true
    default: "latest"
  os:
    description: "OS"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Get full python version
      id: full-python-version
      run: |
        echo ::set-output name=version::$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info[:3]))")
      shell: bash

    - name: Install Poetry ${{ inputs.poetry-version }}
      uses: snok/install-poetry@v1
      with:
        version: ${{ inputs.poetry-version }}
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Check pyproject.toml validity
      run: |
        poetry check --no-interaction
      shell: bash

    - name: Cache dependencies
      id: cache-deps
      uses: actions/cache@v2
      with:
        path: .venv
        key: venv-${{ inputs.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: venv-${{ inputs.os }}-

    - name: Install deps
      run: |
        poetry install --no-interaction
      shell: bash
