name: PyPI Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: ./.github/actions/prepare-workspace
        with:
          python-version: "3.10.0"
          os: "ubuntu-latest"

      - name: Publish to PyPI
        run: |
          poetry config pypi-token.pypi "${{secrets.PYPI_API_TOKEN}}"
          poetry publish --build
