name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  autorelease:
    name: Create Release
    runs-on: "ubuntu-latest"

    services:
      clickhouse:
        image: yandex/clickhouse-server:21.8
        ports:
          - "8123:8123"
          - "9000:9000"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: ./.github/actions/prepare-workspace
        with:
          python-version: "3.10.0"
          os: "ubuntu-latest"

      - name: Add version to environment vars
        run: |
          PROJECT_VERSION=$(poetry version --short)
          echo "PROJECT_VERSION=$PROJECT_VERSION" >> $GITHUB_ENV

      - name: Check if tag version matches project version
        run: |
          TAG=$(git describe HEAD --tags --abbrev=0)
          echo $TAG
          echo $PROJECT_VERSION
          if [[ "$TAG" != "v$PROJECT_VERSION" ]]; then exit 1; fi

      - name: Run tests
        env:
          TEST_CLICKHOUSE_DSN: "clickhouse://localhost:9000/test_migrate"
        run: poetry run pytest -v

      - name: Build
        run: poetry build

      - name: Release Notes
        run: git log $(git describe HEAD~ --tags --abbrev=0)..HEAD --pretty='format:* %h %s%n  * %an <%ae>' --no-merges >> ".github/RELEASE-TEMPLATE.md"

      - name: Create Release Draft
        uses: softprops/action-gh-release@v1
        with:
          body_path: ".github/RELEASE-TEMPLATE.md"
          draft: true
          files: |
            dist/chmigrate-${{ env.PROJECT_VERSION }}-py3-none-any.whl
            dist/chmigrate-${{ env.PROJECT_VERSION }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
